/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class wusong_com_guoluapplication_MainActivity */

#ifndef _Included_wusong_com_guoluapplication_MainActivity
#define _Included_wusong_com_guoluapplication_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     wusong_com_guoluapplication_MainActivity
 * Method:    jniChangeGuolu
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_wusong_com_guoluapplication_MainActivity_jniChangeGuolu
  (JNIEnv *, jobject);

/*
 * Class:     wusong_com_guoluapplication_MainActivity
 * Method:    getProgress
 * Signature: ()V
 */
JNIEXPORT jint JNICALL Java_wusong_com_guoluapplication_MainActivity_getProgress
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
