/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class wusong_com_ccalljava_Jni */

#ifndef _Included_wusong_com_ccalljava_Jni
#define _Included_wusong_com_ccalljava_Jni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     wusong_com_ccalljava_Jni
 * Method:    callBackAdd
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_wusong_com_ccalljava_Jni_callBackAdd
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     wusong_com_ccalljava_Jni
 * Method:    callBackChangeStr
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_wusong_com_ccalljava_Jni_callBackChangeStr
  (JNIEnv *, jobject, jstring);

/*
 * Class:     wusong_com_ccalljava_Jni
 * Method:    callBackChangeArr
 * Signature: ([I)[I
 */
JNIEXPORT jintArray JNICALL Java_wusong_com_ccalljava_Jni_callBackChangeArr
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     wusong_com_ccalljava_Jni
 * Method:    callBackCheckPass
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_wusong_com_ccalljava_Jni_callBackCheckPass
  (JNIEnv *, jobject, jstring);

/*
 * Class:     wusong_com_ccalljava_Jni
 * Method:    callBackSayHello
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT void JNICALL Java_wusong_com_ccalljava_Jni_callBackSayHello
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
