/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class wusong_com_javacallc_Jni */

#ifndef _Included_wusong_com_javacallc_Jni
#define _Included_wusong_com_javacallc_Jni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     wusong_com_javacallc_Jni
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_wusong_com_javacallc_Jni_add
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     wusong_com_javacallc_Jni
 * Method:    addString
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_wusong_com_javacallc_Jni_addString
  (JNIEnv *, jobject, jstring);

/*
 * Class:     wusong_com_javacallc_Jni
 * Method:    changeArray
 * Signature: ([I)[I
 */
JNIEXPORT jintArray JNICALL Java_wusong_com_javacallc_Jni_changeArray
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     wusong_com_javacallc_Jni
 * Method:    checkPass
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_wusong_com_javacallc_Jni_checkPass
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
